# Task Description

In [7]:
# The task would be to test a long-only stock-based carry/value strategy.

# Carry strategy in stocks would be to long high dividend yield stocks and short the reverse (in this case no need to do short).
# Whole value strategy you should be familiar with.

# Carry trade in rate hike periods work pretty well (for fx especially). We are interested in whether the same hold for value. 
# The underlying assets would be S&P 500 stocks.

# Please take into account that some companies do stock repurchase instead of cash dividend.
# You could try to find adjusted dividend yield data. Time horizon is up to you, but keep in mind potential survivorship bias.
# It might be interesting to check the strategy performance during different periods. 
# Remember to make the backtest a way that they could be implemented (not longing 100 stocks at the same time). 
# Have a nice night and good luck with your presentation on Monday.

# Setup

## Load Packages

In [8]:
#### Import required Packages ####
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.dates import DateFormatter
import scipy as sp
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
import sklearn as sk
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error # to calculate the MSE
from sklearn.model_selection import TimeSeriesSplit
from sklearn.model_selection import cross_val_score

from statsmodels.graphics.tsaplots import plot_acf # To produce ACF plots
from statsmodels.graphics.tsaplots import plot_pacf # To produce PACF plots
from statsmodels.tsa.seasonal import seasonal_decompose # To decompose Seasons
from statsmodels.tsa.stattools import adfuller, kpss # Tests for Stationarity
from statsmodels.tsa.ar_model import AutoReg # To produce AR models
from statsmodels.stats.anova import anova_lm # To use ANOVA (compare nested models)
from statsmodels.tsa.arima.model import ARIMA # To build ARMA & ARIMA Models
import statsmodels.stats.diagnostic as dg # To get Breusch-Godfrey Test
from statsmodels.stats.stattools import durbin_watson



from datetime import datetime # to transform variables into datetime objects
import math # simple math functions
from math import sqrt # square root function
import statistics # descriptive statistics library
import scipy.stats as stats # descriptive statistics library from scipy
import matplotlib.dates as mdates # date formatting
from matplotlib.collections import PolyCollection, LineCollection # better plot options

## Plotstyle

In [9]:
# Seaborn plot style ticks to have nicer looking plots
sb.set_style("ticks")
sb.mpl.rc("figure", figsize=(16,8))
sb.mpl.rc("font", size=14)
plt.rcParams['xtick.direction'] = 'in'
plt.rcParams['ytick.direction'] = 'in'

## LoadData

In [12]:
# Loading Data

data_bv = pd.read_excel("02_Data_clean/SPX_BV_per_share_clean.xlsx", parse_dates=["Date"])
data_px = pd.read_excel("02_Data_clean/SPX_PX_Last_clean.xlsx", parse_dates=["Date"])

# Check
print(type(data_bv))
print(data_bv.dtypes)

<class 'pandas.core.frame.DataFrame'>
Date              datetime64[ns]
A UN Equity              float64
AAL UW Equity            float64
AAP UN Equity            float64
AAPL UW Equity           float64
                       ...
YUM UN Equity            float64
ZBH UN Equity            float64
ZBRA UW Equity           float64
ZION UW Equity           float64
ZTS UN Equity            float64
Length: 501, dtype: object

In [13]:
data_px

,Date,A UN Equity,AAL UW Equity,AAP UN Equity,AAPL UW Equity,ABBV UN Equity,ABC UN Equity,ABMD UW Equity,ABT UN Equity,ACGL UW Equity,...,WYNN UW Equity,XEL UW Equity,XOM UN Equity,XRAY UW Equity,XYL UN Equity,YUM UN Equity,ZBH UN Equity,ZBRA UW Equity,ZION UW Equity,ZTS UN Equity
0,2000-01-14,46.0691,NaN,NaN,0.897,NaN,5.3823,21.375,15.4401,1.6528,...,NaN,NaN,41.8750,8.2083,NaN,6.4715,NaN,26.6389,55.6250,NaN
1,2000-01-21,46.3217,NaN,NaN,0.994,NaN,4.6698,29.438,13.9576,1.7361,...,NaN,NaN,42.5000,7.9635,NaN,5.7300,NaN,27.9444,52.8750,NaN
2,2000-01-28,45.8585,NaN,NaN,0.907,NaN,4.5485,29.438,14.2653,1.6806,...,NaN,NaN,39.4375,8.2708,NaN,5.1907,NaN,27.5833,56.1250,NaN
3,2000-02-04,51.3750,NaN,NaN,0.964,NaN,4.4727,27.563,15.4401,1.5556,...,NaN,NaN,40.3438,8.7708,NaN,5.3030,NaN,29.4167,55.3125,NaN
4,2000-02-11,50.7855,NaN,NaN,0.971,NaN,4.0026,29.500,15.5520,1.5764,...,NaN,NaN,36.9375,8.4583,NaN,5.0221,NaN,29.0000,54.6875,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1190,2022-11-04,136.0800,14.11,181.07,138.380,145.28,161.6400,373.990,98.0700,56.8600,...,70.81,65.55,112.3100,27.1500,107.21,121.7800,104.85,230.5600,49.7600,133.67
1191,2022-11-11,148.3100,14.88,186.39,149.700,150.16,153.0100,373.990,104.0900,56.7700,...,77.98,67.49,113.9500,32.0500,111.20,123.3300,115.56,263.3800,55.3900,148.55
1192,2022-11-18,146.1900,14.05,147.50,151.290,154.98,162.0000,377.290,103.8700,57.6700,...,76.00,68.38,112.0800,31.1300,112.63,124.6100,114.09,256.1000,50.6800,145.64
1193,2022-11-25,156.9600,14.50,150.00,148.110,159.62,167.7000,378.080,106.9600,58.7300,...,74.93,69.63,113.2100,31.4800,113.50,126.5300,119.21,271.9000,51.7500,150.10
1194,2022-12-02,155.6700,13.97,153.03,147.810,163.66,173.9900,377.200,108.0900,60.6000,...,85.15,69.14,109.8600,31.6800,113.53,129.6800,122.97,274.8600,52.2500,157.42

## Data Cleaning

In [18]:
# Resample monthly returns
data_px.set_index("Date", inplace=True) # set datetimeindex
mtl_ret = data_px.pct_change(fill_method = None).resample("M").agg(lambda x: ((1+x).prod()-1)) # pct_change creates ordinary returns, resample Monthly and aggregating with the (1+x) -1 formula to get monthly ordinary returns

# df = pd.concat([data, data2], axis=1) # concating dfs

In [27]:
mtl_ret
mtl_ret.drop(mtl_ret.index[0])

,A UN Equity,AAL UW Equity,AAP UN Equity,AAPL UW Equity,ABBV UN Equity,ABC UN Equity,ABMD UW Equity,ABT UN Equity,ACGL UW Equity,ACN UN Equity,...,WYNN UW Equity,XEL UW Equity,XOM UN Equity,XRAY UW Equity,XYL UN Equity,YUM UN Equity,ZBH UN Equity,ZBRA UW Equity,ZION UW Equity,ZTS UN Equity
Date,,,,,,,,,,,,,,,,,,,,,
2000-02-29,0.592287,0.000000,0.000000,0.085998,0.000000,-0.253336,0.278110,0.005881,-0.074378,0.000000,...,0.000000,0.000000,-0.099842,0.027712,0.000000,-0.103897,0.000000,0.015611,-0.109131,0.000000
2000-03-31,-0.040368,0.000000,0.000000,0.231472,0.000000,0.071433,-0.461794,0.097469,0.169581,0.000000,...,0.000000,0.000000,0.095952,0.112741,0.000000,0.200477,0.000000,-0.206744,-0.167500,0.000000
2000-04-30,-0.147838,0.000000,0.000000,-0.086562,0.000000,0.333324,-0.083309,0.092362,-0.060075,0.000000,...,0.000000,0.000000,-0.001606,0.024233,0.000000,0.098587,0.000000,0.140000,-0.003003,0.000000
2000-05-31,-0.274329,0.000000,0.000000,-0.304152,0.000000,0.243750,0.047137,0.084553,-0.009181,0.000000,...,0.000000,0.000000,0.060337,0.077419,0.000000,-0.100727,0.000000,-0.177632,0.082831,0.000000
2000-06-30,0.146744,0.000000,0.000000,0.212711,0.000000,0.246226,-0.209024,0.068961,-0.020479,0.000000,...,0.000000,0.000000,-0.047041,-0.015971,0.000000,-0.079434,0.000000,-0.054667,0.021209,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-08-31,-0.031544,0.002188,-0.103450,0.006830,-0.049892,0.001782,-0.119074,-0.063763,0.047297,-0.026546,...,-0.018116,0.023914,0.009698,-0.070520,0.010214,-0.084707,-0.026089,-0.138472,0.034647,-0.124130
2022-09-30,-0.064064,-0.123726,-0.099372,-0.155360,-0.015695,-0.074287,-0.048272,-0.050442,-0.020645,-0.136954,...,0.011231,-0.145869,-0.107898,-0.156501,-0.060342,-0.051890,-0.027532,-0.149760,-0.098866,-0.072550
2022-10-31,0.141670,0.162791,0.219586,0.126918,0.099844,0.177196,0.050476,0.028214,0.244620,0.118461,...,-0.075044,0.021406,0.267896,0.088536,0.173535,0.108520,0.085318,0.099195,0.013370,0.033650
2022-11-30,0.131080,0.035714,-0.213300,-0.048992,0.081363,0.052665,0.465086,0.075083,0.036168,0.029953,...,0.285249,0.065168,0.022674,0.020091,0.107101,0.073380,0.050586,-0.055903,0.004075,-0.020746
2022-12-31,-0.008219,-0.036552,0.020200,-0.002026,0.025310,0.037507,-0.002328,0.010565,0.031841,0.012584,...,0.136394,-0.007037,-0.029591,0.006353,0.000264,0.024895,0.031541,0.010886,0.009662,0.048767

In [43]:
# Resample monthly returns
qtly_ret = data_px.pct_change(fill_method = None).resample("BQ").agg(lambda x: ((1+x).prod()-1)) # pct_change creates ordinary returns, resample Monthly and aggregating with the (1+x) -1 formula to get monthly ordinary returns

In [42]:
qtly_ret

,A UN Equity,AAL UW Equity,AAP UN Equity,AAPL UW Equity,ABBV UN Equity,ABC UN Equity,ABMD UW Equity,ABT UN Equity,ACGL UW Equity,ACN UN Equity,...,WYNN UW Equity,XEL UW Equity,XOM UN Equity,XRAY UW Equity,XYL UN Equity,YUM UN Equity,ZBH UN Equity,ZBRA UW Equity,ZION UW Equity,ZTS UN Equity
Date,,,,,,,,,,,,,,,,,,,,,
1999-12-31,-0.004571,0.000000,0.000000,0.011148,0.000000,-0.154915,0.377216,-0.076088,0.016820,0.000000,...,0.000000,0.000000,-0.058209,0.007614,0.000000,-0.197914,0.000000,0.035452,0.008989,0.000000
2000-01-31,0.592287,0.000000,0.000000,0.085998,0.000000,-0.253336,0.278110,0.005881,-0.074378,0.000000,...,0.000000,0.000000,-0.099842,0.027712,0.000000,-0.103897,0.000000,0.015611,-0.109131,0.000000
2000-02-29,0.077854,0.000000,0.000000,0.256853,0.000000,0.071433,-0.360452,0.048734,0.107097,0.000000,...,0.000000,0.000000,0.088028,0.049024,0.000000,0.152169,0.000000,-0.183937,-0.148750,0.000000
2000-03-31,-0.230069,0.000000,0.000000,-0.142973,0.000000,0.204161,-0.263641,0.167286,-0.008071,0.000000,...,0.000000,0.000000,0.021846,0.073592,0.000000,0.075478,0.000000,0.060754,0.010279,0.000000
2000-04-28,-0.284920,0.000000,0.000000,-0.273327,0.000000,0.377160,0.097015,0.062103,-0.008137,0.000000,...,0.000000,0.000000,0.043546,0.090317,0.000000,-0.042889,0.000000,-0.140895,0.045058,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-07-29,0.038628,0.004386,-0.092245,0.061847,-0.081633,0.025895,-0.083706,-0.066850,0.064804,0.035138,...,0.009720,0.091161,0.123909,-0.065350,0.102324,-0.061030,0.004766,-0.056692,0.069750,-0.102649
2022-08-31,-0.049203,-0.111354,-0.075408,-0.080614,0.049212,-0.061495,-0.048776,-0.011973,-0.073118,-0.127964,...,-0.042997,-0.044975,-0.123838,-0.108004,-0.033452,-0.013463,-0.012092,-0.130192,-0.034018,-0.061542
2022-09-30,0.123826,0.146601,0.187975,0.035299,0.031805,0.161152,0.051032,-0.011820,0.315081,0.106931,...,-0.022632,-0.086501,0.290962,0.029353,0.140886,0.065341,0.068355,0.074466,-0.054659,0.021526
2022-10-31,0.131080,0.035714,-0.213300,-0.048992,0.081363,0.052665,0.465086,0.075083,0.036168,0.029953,...,0.285249,0.065168,0.022674,0.020091,0.107101,0.073380,0.050586,-0.055903,0.004075,-0.020746
2022-11-30,-0.008219,-0.036552,0.020200,-0.002026,0.025310,0.037507,-0.002328,0.010565,0.031841,0.012584,...,0.136394,-0.007037,-0.029591,0.006353,0.000264,0.024895,0.031541,0.010886,0.009662,0.048767

In [31]:
data_bv

,Date,A UN Equity,AAL UW Equity,AAP UN Equity,AAPL UW Equity,ABBV UN Equity,ABC UN Equity,ABMD UW Equity,ABT UN Equity,ACGL UW Equity,...,WYNN UW Equity,XEL UW Equity,XOM UN Equity,XRAY UW Equity,XYL UN Equity,YUM UN Equity,ZBH UN Equity,ZBRA UW Equity,ZION UW Equity,ZTS UN Equity
0,2000-04-30,10.2637,45.1727,NaN,0.2231,NaN,1.0496,5.4237,5.2805,2.2841,...,NaN,17.5533,9.6066,3.0943,NaN,-0.8699,NaN,5.0004,19.0605,NaN
1,2000-07-31,10.8208,47.0704,NaN,0.2213,NaN,1.0496,5.6309,5.3760,2.4037,...,NaN,16.1490,9.7973,3.1181,NaN,-0.7671,NaN,5.1342,19.7288,NaN
2,2000-10-31,11.5975,47.1910,NaN,0.2144,NaN,1.5347,5.4334,5.5442,2.3806,...,NaN,16.3182,10.2102,3.3551,NaN,-0.5476,NaN,5.4125,20.4230,NaN
3,2001-01-31,12.1308,47.0611,NaN,0.1918,NaN,1.5373,4.8026,5.2314,2.3599,...,NaN,17.1020,10.4187,3.4591,NaN,-0.3639,NaN,5.6562,22.9856,NaN
4,2001-04-30,12.2869,43.6506,NaN,0.1926,NaN,1.9006,4.9289,5.5183,2.3465,...,NaN,17.5062,10.6764,3.6208,NaN,-0.1990,1.2721,5.8899,23.8034,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,2021-07-31,16.3234,-11.4861,51.9940,3.8824,7.6649,1.0734,30.4323,19.4663,32.4268,...,-0.4603,28.1748,37.9284,23.4309,17.1547,-26.7177,61.2168,52.6807,46.8536,9.8844
86,2021-10-31,17.8444,-11.3319,51.2159,3.8407,8.7133,1.1555,31.4821,20.2950,33.5579,...,-1.8530,28.6972,39.7681,22.8974,17.8381,-28.9723,60.5775,55.8642,46.3218,9.6133
87,2022-01-31,17.1800,-13.7645,50.4490,4.4020,9.2157,2.6280,33.0075,20.2171,32.1762,...,-2.9076,28.8909,40.1650,22.5661,17.7568,-29.6888,57.3259,55.0537,38.6791,9.8852
88,2022-04-30,17.1304,-12.9613,47.6232,4.1585,8.2878,1.0791,33.7129,20.8369,31.3731,...,-5.3590,29.2077,42.5422,22.5186,17.7401,-30.0632,57.8168,48.3688,34.5050,9.7735
89,2022-07-31,17.1993,-12.1456,46.4887,3.6102,9.0443,-1.0260,34.0872,20.4608,29.6898,...,-6.7313,29.9521,45.1918,22.5186,17.8413,-30.0775,58.3637,51.2779,28.4471,9.9970

In [ ]:
# Think about Log-Diff Variables
df["ln_initial_claims"] = np.log(df['initial_claims']) 
df["ln_orders_cap"] = np.log(df['orders_cap'])
df["ln_orders_CG"] = np.log(df['orders_CG'])